model:
    arch: segnet
    add_dropout: True
    dropout_rate: 0.5
data:
    dataset: camvid
    train_split: train
    val_split: test
    img_rows: 360
    img_cols: 480
    path: /home/eddie/dataset/CamVid
    ignore_index: [11]
    
training:
    train_iters: 100000
    batch_size: 3
    val_interval: 1000
    n_workers: 8
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        momentum: 0.9
        weight_decay: 0.0005
        # betas: [0.9, 0.999]
    lr_schedule:
        name: 'poly_lr'
        max_iter: 100000
    loss:
        name: 'cross_entropy'
        size_average: True
        weight: [0.2595, 0.1826, 4.5640, 0.1417, 0.9051, 0.3826, 9.6446, 1.8418, 0.6823, 6.2478, 7.3614]
    resume: camvid_segnet_best_model.pkl
    visdom: False